### ISSUE TITLE
fix everything

### ISSUE THREAD

**Issue by shmemcat** [PrinceWalnut/advent_of_code#1]
it's all shit

**Comment by shmemcat** [comment]
@PrinceWalnut I'm going to need an accurate time estimate, we do have a schedule to stick to here

**Comment by PrinceWalnut** [comment]
> 

I'm going to need a fuck to give

**Comment by shmemcat** [comment]
![image](https://user-images.githubusercontent.com/14319144/147433504-3c438f00-8ffe-46e6-b34a-0492300d850e.png)

**Comment by PrinceWalnut** [comment]
Thanks. If you'd like to file a bug report, I recommend just going to your root directory and running `rm -rf *` first to clear out the cache. If the problem persists, feel free to open another issue once you reinstall your OS

**Comment by shmemcat** [comment]
HEY THIS DOESN'T RUN ON MY MACHINE BITCH

**Comment by PrinceWalnut** [comment]
> HEY THIS DOESN'T RUN ON MY MACHINE BITCH

Try this:

`sudo dnf install brain`

**Comment by shmemcat** [comment]
try not being fat and ugly

**Comment by PrinceWalnut** [comment]
> try not being fat and ugly

Try getting a real markdown cheat sheet
